### ISSUE TITLE
Please allow filtering of marathon.json

### ISSUE THREAD

**Issue by KnisterPeter** [holidaycheck/marathon-maven-plugin#4]
Hi there,

it would be awesome to allow filtering of the marathon config file via maven.
This way the docker image (if any) could be set as a property in the maven pom.xml and be used by the docker-maven-plugin and the marathon-maven-plugin and need only be set in one location.

**Comment by krystiannowak** [comment]
I would be happy to accept your PR if you can provide it.

**Comment by KnisterPeter** [comment]
I would close this one since it is already possible if one uses the maven resource infrastructure to pre-filter the marathon.json. Therefore we don't need this option.

**Comment by krystiannowak** [comment]
@KnisterPeter thanks for the hint on resources preprocessing anyway - makes more sense (standardized)
